basePath: /
definitions:
  models.BankResponse:
    properties:
      status:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Payment:
    properties:
      amount:
        type: number
      card_number:
        type: string
      created_at:
        type: string
      currency:
        type: string
      deleted_at:
        type: string
      expiry_month:
        type: string
      expiry_year:
        type: string
      id:
        type: integer
      status:
        type: string
      updated_at:
        type: string
    type: object
  models.ProcessPaymentRequest:
    properties:
      amount:
        type: number
      card_number:
        type: string
      currency:
        type: string
      cvv:
        type: string
      expiry_month:
        type: string
      expiry_year:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a payment gateway.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Payment Gateway API
  version: "1.0"
paths:
  /process_payment:
    post:
      consumes:
      - application/json
      description: Process a payment with card details
      parameters:
      - description: Payment request
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/models.ProcessPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BankResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Process a payment
      tags:
      - payment
  /retrieve_payment/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve details of a previously made payment using its identifier
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Payment'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Retrieve payment details
      tags:
      - payment
swagger: "2.0"
